---
abstract: 'Add a debian/control file to your distribution '
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Control-Debian
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - inc
  package:
    - DB
provides:
  Dist::Zilla::Plugin::Control::Debian:
    file: lib/Dist/Zilla/Plugin/Control/Debian.pm
    version: 0.001
requires:
  Dist::Zilla::Role::FileGatherer: 0
  Moose: 0
  Moose::Autobox: 0
  Software::Release: 0
  Software::Release::Change: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/dist-zilla-plugin-control-debian/issues
  homepage: https://metacpan.org/release/Dist-Zilla-Plugin-Control-Debian
  repository: git://github.com/shantanubhadoria/dist-zilla-plugin-control-debian.git
version: 0.001
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
